# -*- coding: utf-8 -*-
"""Job Search Final Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MRaHnM7woHyvVnYTujpqAtmwkDMoVw-m
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import uuid

#Using device: CUDA

# --- Dataset Loading and Preprocessing ---
def load_and_preprocess_datasets(candidates_path, jobs_path):
    # Load datasets
    candidates_df = pd.read_csv(candidates_path)
    jobs_df = pd.read_csv(jobs_path, on_bad_lines='skip', quotechar='"')

    # Preprocess candidates
    candidates_df = candidates_df.rename(columns={
        'HaveWorkedWith': 'skills',  # Adjust if column name differs
        'YearsCodePro': 'experience',
        'PreviousSalary': 'preferred_salary'
    })
    # If location is not available, set to 'Unknown'
    candidates_df['preferred_location'] = candidates_df.get('Location', 'Unknown')

    # Handle skills (convert to string if list or comma-separated)
    candidates_df['skills'] = candidates_df['skills'].fillna('').astype(str).apply(lambda x: ' '.join(x.split(',')) if ',' in x else x)

    # Handle missing values
    candidates_df['experience'] = pd.to_numeric(candidates_df['experience'], errors='coerce').fillna(candidates_df['experience'].mean())
    candidates_df['preferred_salary'] = pd.to_numeric(candidates_df['preferred_salary'], errors='coerce').fillna(candidates_df['preferred_salary'].mean())
    candidates_df['preferred_location'] = candidates_df['preferred_location'].fillna('Unknown')

    # Preprocess jobs
    jobs_df = jobs_df.rename(columns={
        'skills': 'required_skills',
        'Experience': 'required_experience',
        'Location': 'location',
        'Salary Range': 'salary',
        'Role': 'industry'  # Using Role as proxy for industry
    })

    # Parse Salary Range (e.g., '$60k-$80k' -> 70000)
    def parse_salary(salary):
        try:
            if isinstance(salary, str):
                # Remove '$' and 'k', split range
                salary = salary.replace('$', '').replace('k', '000')
                if '-' in salary:
                    low, high = salary.split('-')
                    return (float(low) + float(high)) / 2
                return float(salary)
            return float(salary)
        except:
            return np.nan

    jobs_df['salary'] = jobs_df['salary'].apply(parse_salary)

    # Handle skills
    jobs_df['required_skills'] = jobs_df['required_skills'].fillna('').astype(str).apply(lambda x: ' '.join(x.split(',')) if ',' in x else x)

    # Handle missing values
    jobs_df['required_experience'] = jobs_df['required_experience'].str.extract(r'(\d+)\sto\s(\d+)\sYears').astype(float).mean(axis=1)
    jobs_df['required_experience'] = pd.to_numeric(jobs_df['required_experience'], errors='coerce').fillna(jobs_df['required_experience'].mean())
    jobs_df['salary'] = jobs_df['salary'].fillna(jobs_df['salary'].mean())
    jobs_df['location'] = jobs_df['location'].fillna('Unknown')
    jobs_df['industry'] = jobs_df['industry'].fillna('Unknown')

    return candidates_df, jobs_df

# --- Generate Synthetic Labels for Candidate-Job Pairs ---
def generate_labels(candidates_df, jobs_df, n_pairs=1000):
    np.random.seed(42)
    labels = []
    paired_candidates = []
    paired_jobs = []

    for _ in range(n_pairs):
        # Randomly pair a candidate and job
        candidate = candidates_df.sample(1).iloc[0]
        job = jobs_df.sample(1).iloc[0]

        # Calculate match score based on feature similarity
        skill_overlap = len(set(candidate['skills'].split()) & set(job['required_skills'].split())) / max(len(job['required_skills'].split()), 1)
        exp_diff = 1 - abs(candidate['experience'] - job['required_experience']) / 15
        salary_diff = 1 - abs(candidate['preferred_salary'] - job['salary']) / 100000
        location_match = 1 if candidate['preferred_location'] == job['location'] else 0

        match_score = (
            skill_overlap * 0.5 +
            exp_diff * 0.3 +
            salary_diff * 0.1 +
            location_match * 0.1
        )
        label = 1 if match_score > 0.6 else 0

        paired_candidates.append(candidate)
        paired_jobs.append(job)
        labels.append(label)

    return pd.DataFrame(paired_candidates), pd.DataFrame(paired_jobs), pd.Series(labels)

# --- Dataset Class ---
class JobRecommendationDataset(Dataset):
    def __init__(self, candidates, jobs, labels, tokenizer, max_len=128):
        self.candidates = candidates
        self.jobs = jobs
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len
        self.scaler = StandardScaler()

        # Normalize numerical features
        numerical_features = self.scaler.fit_transform(
            candidates[['experience', 'preferred_salary']].join(
                jobs[['required_experience', 'salary']])
        )
        self.candidates['experience'] = numerical_features[:, 0]
        self.candidates['preferred_salary'] = numerical_features[:, 1]
        self.jobs['required_experience'] = numerical_features[:, 2]
        self.jobs['salary'] = numerical_features[:, 3]

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        candidate = self.candidates.iloc[idx]
        job = self.jobs.iloc[idx]
        label = self.labels.iloc[idx]

        # Combine text features
        candidate_text = f"{candidate['skills']} [SEP] {candidate['preferred_location']}"
        job_text = f"{job['required_skills']} [SEP] {job['location']} [SEP] {job['industry']}"

        # Tokenize
        candidate_encoding = self.tokenizer(
            candidate_text, max_length=self.max_len, padding='max_length', truncation=True, return_tensors='pt'
        )
        job_encoding = self.tokenizer(
            job_text, max_length=self.max_len, padding='max_length', truncation=True, return_tensors='pt'
        )

        # Numerical features
        numerical = torch.tensor([
            candidate['experience'], candidate['preferred_salary'],
            job['required_experience'], job['salary']
        ], dtype=torch.float)

        return {
            'candidate_input_ids': candidate_encoding['input_ids'].squeeze(),
            'candidate_attention_mask': candidate_encoding['attention_mask'].squeeze(),
            'job_input_ids': job_encoding['input_ids'].squeeze(),
            'job_attention_mask': job_encoding['attention_mask'].squeeze(),
            'numerical': numerical,
            'label': torch.tensor(label, dtype=torch.float)
        }

# --- Transformer Model ---
class JobRecommendationTransformer(nn.Module):
    def __init__(self, vocab_size, d_model=128, nhead=4, num_layers=2, dim_feedforward=512, dropout=0.1):
        super(JobRecommendationTransformer, self).__init__()
        self.embedding = nn.Embedding(vocab_size, d_model)
        self.pos_encoder = nn.Parameter(torch.zeros(1, 128, d_model))
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model, nhead=nhead, dim_feedforward=dim_feedforward, dropout=dropout, batch_first=True
        )
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        # Numerical feature processing
        self.numerical_fc = nn.Linear(4, d_model)

        # Classification head
        self.fc = nn.Sequential(
            nn.Linear(d_model * 2, 128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, 1),
            nn.Sigmoid()
        )

        self.d_model = d_model

    def forward(self, candidate_ids, candidate_mask, job_ids, job_mask, numerical):
        # Candidate encoding
        candidate_emb = self.embedding(candidate_ids) * torch.sqrt(torch.tensor(self.d_model, dtype=torch.float))
        candidate_emb = candidate_emb + self.pos_encoder[:, :candidate_ids.size(1), :]
        candidate_mask = (candidate_mask == 0)
        candidate_out = self.transformer_encoder(candidate_emb, src_key_padding_mask=candidate_mask)
        candidate_pooled = candidate_out[:, 0, :]  # CLS token

        # Job encoding
        job_emb = self.embedding(job_ids) * torch.sqrt(torch.tensor(self.d_model, dtype=torch.float))
        job_emb = job_emb + self.pos_encoder[:, :job_ids.size(1), :]
        job_mask = (job_mask == 0)
        job_out = self.transformer_encoder(job_emb, src_key_padding_mask=job_mask)
        job_pooled = job_out[:, 0, :]  # CLS token

        # Numerical features
        numerical_out = self.numerical_fc(numerical)

        # Combine embeddings
        combined = torch.cat([candidate_pooled + numerical_out, job_pooled + numerical_out], dim=-1)

        # Compute similarity and probability
        prob = self.fc(combined).squeeze()

        return prob, candidate_pooled, job_pooled

# --- Training Function ---
def train_model(model, train_loader, val_loader, epochs=10, device='cuda' if torch.cuda.is_available() else 'cpu'):
    model = model.to(device)
    optimizer = optim.Adam(model.parameters(), lr=1e-4)
    criterion = nn.BCELoss()

    for epoch in range(epochs):
        model.train()
        train_loss = 0
        train_correct = 0
        train_total = 0

        for batch in train_loader:
            optimizer.zero_grad()
            candidate_ids = batch['candidate_input_ids'].to(device)
            candidate_mask = batch['candidate_attention_mask'].to(device)
            job_ids = batch['job_input_ids'].to(device)
            job_mask = batch['job_attention_mask'].to(device)
            numerical = batch['numerical'].to(device)
            labels = batch['label'].to(device)

            # Clamp labels to be within [0, 1]
            labels = torch.clamp(labels, 0, 1) # This line is added!

            prob, _, _ = model(candidate_ids, candidate_mask, job_ids, job_mask, numerical)
            loss = criterion(prob, labels)

            loss.backward()
            optimizer.step()

            train_loss += loss.item()
            predicted = (prob > 0.5).float()
            train_correct += (predicted == labels).sum().item()
            train_total += labels.size(0)

        # Validation
        model.eval()
        val_loss = 0
        val_correct = 0
        val_total = 0
        with torch.no_grad():
            for batch in val_loader:
                candidate_ids = batch['candidate_input_ids'].to(device)
                candidate_mask = batch['candidate_attention_mask'].to(device)
                job_ids = batch['job_input_ids'].to(device)
                job_mask = batch['job_attention_mask'].to(device)
                numerical = batch['numerical'].to(device)
                labels = batch['label'].to(device)

                prob, _, _ = model(candidate_ids, candidate_mask, job_ids, job_mask, numerical)
                loss = criterion(prob, labels)

                val_loss += loss.item()
                predicted = (prob > 0.5).float()
                val_correct += (predicted == labels).sum().item()
                val_total += labels.size(0)

        print(f"Epoch {epoch+1}/{epochs}:")
        print(f"Train Loss: {train_loss/len(train_loader):.4f}, Accuracy: {train_correct/train_total:.4f}")
        print(f"Val Loss: {val_loss/len(val_loader):.4f}, Accuracy: {val_correct/val_total:.4f}")

# --- Inference Function ---
def recommend_jobs(model, candidate, jobs, tokenizer, scaler, max_len=128, device='cuda' if torch.cuda.is_available() else 'cpu'):
    model.eval()
    recommendations = []

    # Normalize candidate numerical features
    numerical_features = scaler.transform(
        pd.DataFrame([candidate])[ ['experience', 'preferred_salary'] ].join(
            jobs[['required_experience', 'salary']])
    )

    with torch.no_grad():
        for idx, job in jobs.iterrows():
            candidate_text = f"{candidate['skills']} [SEP] {candidate['preferred_location']}"
            job_text = f"{job['required_skills']} [SEP] {job['location']} [SEP] {job['industry']}"

            candidate_encoding = tokenizer(
                candidate_text, max_length=max_len, padding='max_length', truncation=True, return_tensors='pt'
            )
            job_encoding = tokenizer(
                job_text, max_length=max_len, padding='max_length', truncation=True, return_tensors='pt'
            )

            numerical = torch.tensor(numerical_features[idx], dtype=torch.float)

            prob, candidate_emb, job_emb = model(
                candidate_encoding['input_ids'].to(device),
                candidate_encoding['attention_mask'].to(device),
                job_encoding['input_ids'].to(device),
                job_encoding['attention_mask'].to(device),
                numerical.to(device)
            )

            similarity = torch.cosine_similarity(candidate_emb, job_emb, dim=-1).item()
            recommendations.append({
                'job': job.to_dict(),
                'match_probability': prob.item(),
                'similarity': similarity
            })

    return sorted(recommendations, key=lambda x: x['match_probability'], reverse=True)

# Commented out IPython magic to ensure Python compatibility.
# %env CUDA_LAUNCH_BLOCKING=1

print("Moving model to device:", device)

for data, target in train_loader:
  print(f"Data shape: {data.shape}, Target shape: {target.shape}")
  print(f"Sample target values: {target[:5]}")
  break
  X= np.nan_to_num(X, nan=0.0, posinf=1e6, neginf=-1e6)

if __name__ == "__main__":
    # Load and preprocess datasets
    candidates_df, jobs_df = load_and_preprocess_datasets('/content/Candidate Profile.csv', '/content/job_descriptions.csv')

    # Generate candidate-job pairs and synthetic labels
    candidates_df, jobs_df, labels = generate_labels(candidates_df, jobs_df, n_pairs=1000)

    # Split data
    train_candidates, test_candidates, train_jobs, test_jobs, train_labels, test_labels = train_test_split(
        candidates_df, jobs_df, labels, test_size=0.2, random_state=42
    )
    train_candidates, val_candidates, train_jobs, val_jobs, train_labels, val_labels = train_test_split(
        train_candidates, train_jobs, train_labels, test_size=0.25, random_state=42
    )

    # Initialize tokenizer
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

    # Create datasets
    train_dataset = JobRecommendationDataset(train_candidates, train_jobs, train_labels, tokenizer)
    val_dataset = JobRecommendationDataset(val_candidates, val_jobs, val_labels, tokenizer)
    test_dataset = JobRecommendationDataset(test_candidates, test_jobs, test_labels, tokenizer)

    # Create data loaders
    train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=16)
    test_loader = DataLoader(test_dataset, batch_size=16)

    # Initialize model
    model = JobRecommendationTransformer(vocab_size=tokenizer.vocab_size)

    # Train model
    train_model(model, train_loader, val_loader)

    # Example inference
    sample_candidate = {
        'skills': 'Python SQL Machine Learning',
        'experience': 5,
        'preferred_location': 'United States',
        'preferred_salary': 100000
    }
    recommendations = recommend_jobs(model, sample_candidate, test_jobs, tokenizer, train_dataset.scaler)

    print("\nTop 5 Job Recommendations:")
    for rec in recommendations[:5]:
        print(f"Job: {rec['job']['required_skills']} | Location: {rec['job']['location']} | "
              f"Match Probability: {rec['match_probability']:.4f} | Similarity: {rec['similarity']:.4f}")